---
apiVersion: v1
kind: Namespace
metadata:
  name: security-qe-golden-path
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-qe-golden-path
  namespace: openshift-gitops
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
  source:
    repoURL: https://github.com/lijcam/security-qe-golden-path.git
    targetRevision: HEAD
    path: Content/Pipeline
  destination:
    namespace: security-qe-golden-path
    server: https://kubernetes.default.svc