---
apiVersion: v1
kind: Namespace
metadata:
  name: rhacs-operator
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhacs-operator
  namespace: rhacs-operator
  labels:
    operators.coreos.com/rhacs-operator.rhacs-operator: ""
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace