apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: secure-build-template
spec:
  params:
  - description: The git branch for this PR.
    name: io.openshift.build.commit.ref
  - description: the specific commit SHA.
    name: io.openshift.build.commit.id
  - description: The date at which the commit was made
    name: io.openshift.build.commit.date
  - description: The name of the github user handle that made the commit
    name: io.openshift.build.commit.author
  - description: The commit message
    name: io.openshift.build.commit.message
  - description: The git repository URL.
    name: gitrepositoryurl
  - description: The repository name for this PullRequest.
    name: fullname
  - description: The repository to push built images to.
    name: imageRepoDev
  - description: The repository to push built images to.
    name: imageRepoProd
  - description: Enable image repository TLS certification verification.
    name: tlsVerify
  - description: Extra parameters passed for the push command when pushing images.
    name: build_extra_args
  - description: Target image repository name
    name: imageRepo
#  - description: Sonarqube host url
#    name: sonarqubeHostUrl
#  - description: Cyclonedx host url
#    name: cyclonedxHostUrl
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: secure-build-pipeline-
    spec:
      params:
      - name: GIT_REPO
        value: $(tt.params.gitrepositoryurl)
      - name: TLSVERIFY
        value: $(tt.params.tlsVerify)
      - name: BUILD_EXTRA_ARGS
        value: $(tt.params.build_extra_args)
      - name: IMAGE_REPO
        value: $(tt.params.imageRepo)
      - name: IMAGE_TAG
        value: $(tt.params.io.openshift.build.commit.ref)-$(tt.params.io.openshift.build.commit.id)
      - name: COMMIT_SHA
        value: $(tt.params.io.openshift.build.commit.id)
      - name: GIT_REF
        value: $(tt.params.io.openshift.build.commit.ref)
      - name: COMMIT_DATE
        value: $(tt.params.io.openshift.build.commit.date)
      - name: COMMIT_AUTHOR
        value: $(tt.params.io.openshift.build.commit.author)
      - name: COMMIT_MESSAGE
        value: $(tt.params.io.openshift.build.commit.message)
#      - name: SONARQUBE_HOST_URL
#        value: $(tt.params.sonarqubeHostUrl)
#      - name: SONARQUBE_PROJECT_KEY
#        value: globex-ui
#      - name: SONARQUBE_PROJECT_SECRET
#        value: globex-ui-sonarqube-secret
#      - name: CYCLONEDX_HOST_URL
#        value: $(tt.params.cyclonedxHostUrl)
      pipelineRef:
        name: secure-build-pipeline
      serviceAccountName: pipeline
      workspaces:
        - name: shared-data
          volumeClaimTemplate:
            metadata:
              creationTimestamp: null
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 3Gi
            status: {}
        - emptyDir: {}
          name: maven-settings
        - emptyDir: {}
          name: signature
        - name: secrets
          secret:
            secretName: gpg-public-key