kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline
secrets:
  - name: image-registry-secret
  - name: stackrox-endpoint
  - name: stackrox-secret
imagePullSecrets:
  - name: image-registry-secret