kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline
  namespace: security-qe-golden-path
secrets:
  - name: image-registry-secret
  - name: rox-central-endpoint
  - name: rox-api-token
imagePullSecrets:
  - name: image-registry-secret